# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/negroni/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/negroni

PRODUCT_COPY_FILES += \
    vendor/oneplus/negroni/proprietary/odm/etc/acdbdata/Audio_Parameter_Version.txt:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Audio_Parameter_Version.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/oneplus/negroni/proprietary/odm/etc/camera/config/camera_unit_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_config \
    vendor/oneplus/negroni/proprietary/odm/etc/camera/config/oplus_camera_aps_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_aps_config \
    vendor/oneplus/negroni/proprietary/odm/etc/camera/config/oplus_camera_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_config \
    vendor/oneplus/negroni/proprietary/odm/etc/camera/settings_fdc.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/settings_fdc.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Calibration360_2mic.dat:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Calibration360_2mic.dat \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Configuration.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Configuration.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID10_MIC_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID10_MIC_VR.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID11_HE.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID11_HE.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID12_HE_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID12_HE_APP1.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID13_HE_APP2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID13_HE_APP2.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID14_HE_Cam.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID14_HE_Cam.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID15_HE_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID15_HE_Conference.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID16_HE_Fast.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID16_HE_Fast.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID17_HE_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID17_HE_Interview.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID18_HE_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID18_HE_Unprocess.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID19_HE_Voice.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID19_HE_Voice.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID1_MIC_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID1_MIC_Normal.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID20_HE_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID20_HE_VR.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID21_USB_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID21_USB_Normal.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID22_USB_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID22_USB_APP1.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID23_BT_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID23_BT_Normal.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID24_BT_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID24_BT_APP1.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID2_MIC_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID2_MIC_APP1.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID3_MIC_APP2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID3_MIC_APP2.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID4_MIC_Cam.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID4_MIC_Cam.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID5_MIC_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID5_MIC_Conference.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID6_MIC_Fast.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID6_MIC_Fast.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID7_MIC_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID7_MIC_Interview.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID8_MIC_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID8_MIC_Unprocess.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID9_MIC_Voice.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID9_MIC_Voice.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/3mic/LVACFS_Calibration360_3mic.dat:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/3mic/LVACFS_Calibration360_3mic.dat \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/3mic/LVACFS_Configuration.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/3mic/LVACFS_Configuration.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/3mic/LVACFS_Parameter_3mic_surround.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/3mic/LVACFS_Parameter_3mic_surround.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/3mic/LVACFS_Parameter_3mic_track.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/3mic/LVACFS_Parameter_3mic_track.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/3mic/LVACFS_Parameter_3mic_zoom.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/3mic/LVACFS_Parameter_3mic_zoom.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/3mic/audiozoom_1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/3mic/audiozoom_1.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/3mic/audiozoom_2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/3mic/audiozoom_2.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/lvacfs_params/3mic/audiozoom_3.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/3mic/audiozoom_3.txt \
    vendor/oneplus/negroni/proprietary/odm/etc/sensor/config/waipio_qrd_ak0991x.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/waipio_qrd_ak0991x.json \
    vendor/oneplus/negroni/proprietary/odm/etc/sensor/config/waipio_qrd_alsps.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/waipio_qrd_alsps.json \
    vendor/oneplus/negroni/proprietary/odm/etc/sensor/config/waipio_qrd_bmp380.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/waipio_qrd_bmp380.json \
    vendor/oneplus/negroni/proprietary/odm/etc/sensor/config/waipio_qrd_cct_rear.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/waipio_qrd_cct_rear.json \
    vendor/oneplus/negroni/proprietary/odm/etc/sensor/config/waipio_qrd_icm4x6xx.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/waipio_qrd_icm4x6xx.json \
    vendor/oneplus/negroni/proprietary/odm/etc/sensor/config/waipio_qrd_lps22hb.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/waipio_qrd_lps22hb.json \
    vendor/oneplus/negroni/proprietary/odm/etc/sensor/config/waipio_qrd_lsm6dso_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/waipio_qrd_lsm6dso_0.json \
    vendor/oneplus/negroni/proprietary/odm/etc/sensor/config/waipio_qrd_mmc56x3x.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/waipio_qrd_mmc56x3x.json \
    vendor/oneplus/negroni/proprietary/odm/etc/sensor/config/waipio_qrd_sx933x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/waipio_qrd_sx933x_0.json \
    vendor/oneplus/negroni/proprietary/odm/etc/sensor/config/waipio_qrd_sx933x_down_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/waipio_qrd_sx933x_down_0.json \
    vendor/oneplus/negroni/proprietary/odm/etc/sensor/sensor_config.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/sensor_config.json \
    vendor/oneplus/negroni/proprietary/odm/etc/wifi/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/bdwlan.elf \
    vendor/oneplus/negroni/proprietary/odm/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_ODM)/firmware/tfa98xx.cnt
